const ROUTER = {
  HOME: 'Home',
  PROFILE: 'Profile',
  MESSAGES: 'Messages',
  EXPLORE: 'Explore',
  BOOKINGS: 'Bookings',
  BOOKING_DEAIL: 'Booking Detail',
  MY_SHERPAS: 'My Sherpas',
  SIGN_UP: 'Signup',
  SIGN_IN: 'Signin',
  FORGOT_PASSWORD: "Forgot Password?",
  EMAIL_VERTIFICATION: "Email Verification",
  RESET_PASSWORD: "Create New Password",
  CHANGE_PASSWORD: 'Change Password',
  REGISTER_SHERPA: 'Register to become a Sherpa',
  USER_DETAIL: 'User Detail',
  EDIT_GALLERY: 'Edit Gallery',
  FIND_SHERPA: 'Find a Sherpa',
  SERVICE_DETAIL: 'Service Detail',
  SERVICE_REQUEST: 'Let’s Request',
  CHECKOUT: 'Checkout',
  MY_CARD: 'My Card',
  SUPPORT: 'Support',
};
export default ROUTER;
